<?php $this->headTitle('Index'); ?>

<div class="container-fluid wrapper">
    <h3>Secret Paper</h3>
    <form enctype="multipart/form-data" action="/" method="post">
        <input type="hidden" name="MAX_FILE_SIZE" value="5242880" />

        <input type="file" id="files" name="uploadFile" accept="application/pdf" />
        <label for="files">
            <i class="fas fa-cloud-upload-alt"></i>
            choose a pdf file to upload
        </label>
        <button>Submit</button>
    </form>
</div>
