<?php $this->headTitle('Index'); ?>

<div class="container-fluid">
    <h1><?= $this->fake ?></h1>
    <h3>Secret Paper</h3>
    <h5>Upload a File</h5>
    <form enctype="multipart/form-data" action="/file" method="post">
        <input type="hidden" name="MAX_FILE_SIZE" value="5242880" />
        <label for="uploadFile">Choose file to upload</label>
        <input type="file" id="uploadFile" name="uploadFile" accept="application/pdf"/><br><br>
        <button>Submit</button>
    </form>
    <p>
        <a href="#">Or paste your Document</a>
    </p>
</div>
