<?php
$this->headLink()
    ->prependStylesheet('/assets/css/default.css')
    ->prependStylesheet('/assets/vendor/fontawesome/css/solid.min.css')
    ->prependStylesheet('/assets/vendor/fontawesome/css/brands.min.css')
    ->prependStylesheet('/assets/vendor/fontawesome/css/fontawesome.min.css')
    ->prependStylesheet('/assets/vendor/bootstrap-icons/bootstrap-icons.css')
    ->prependStylesheet('/assets/vendor/bootstrap/css/bootstrap.min.css');
$this->inlineScript()
    ->prependFile('/assets/vendor/bootstrap/js/bootstrap.bundle.min.js')
    ->prependFile('/assets/vendor/jquery/jquery.min.js');
?>
<!DOCTYPE html>
<html lang="de">
    <head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="robots" content="noindex" />
        <meta name ="description" content = "Secret Paper - Hackathon Project at Nov 2021 - Topic Secret Sharing" />
        <meta name="theme-color" content="#1a1e21" />
        <link rel="icon" href="/assets/img/favicon.ico" type="image/x-icon" />
        <?=$this->headMeta()?>
        <?=$this->headLink()?>
        <title>Secret Paper</title>
    </head>

    <body>
        <main class="container-fluid content">
            <?=$this->content?>
        </main>

        <?=$this->inlineScript()?>
    </body>
</html>


